export const lessonPrincipleGroups = [
  {
    id: 'khai',
    title: 'Khai cuộc',
    items: [
      'Khai cuộc ưu tiên xuất xe, thông mã, giữ pháo có mục tiêu rõ ràng',
      'Không tham tốt biên nếu xe mã còn kẹt trong nhà',
      'Pháo đầu mạnh khi có quân phối hợp, yếu dần nếu đi sâu một mình',
      'Bình Phong Mã cần giữ thế liên hoàn giữa mã, tượng và xe phản kích',
      'Thuận Pháo là cuộc đua tốc độ ra xe, không chỉ là đổi pháo trung lộ',
      'Nghịch Pháo dễ thành đối công, nên từng nhịp xuất quân đều phải có tempo',
      'Tiến binh trong khai cuộc là để mở đường và tranh điểm, không phải đẩy liên tục',
      'Phi Tượng chỉ chắc khi đi kèm phát triển mã và xe, không nên chỉ dựng khung thủ',
      'Đổi pháo quá sớm thường giúp đối phương giải phóng trung lộ',
      'Mở trung lộ xong phải nhanh chóng đưa xe hoặc mã vào tiếp ứng',
      'Xe ra đúng cánh sẽ biến thế chắc thành phản kích có lực',
      'Một nhịp xuất xe thường đáng hơn một tốt lẻ trong khai cuộc',
    ],
  },
  {
    id: 'trung',
    title: 'Trung cuộc',
    items: [
      'Trung cuộc quan trọng nhất là phối hợp: một quân đi phải mở đường cho quân sau',
      'Khi đang ép thế, ưu tiên tăng quân vào trận trước khi đổi quân',
      'Không ăn quân nếu quân chủ lực đi sâu mà thiếu đường tiếp ứng',
      'Binh qua sông có giá trị khi ép điểm yếu hoặc làm ngòi cho pháo',
      'Mã khống chế điểm chéo, pháo đánh theo tuyến, xe cắt đường ngang dọc',
      'Đòn mở tuyến mạnh khi vừa tạo uy hiếp trực tiếp vừa mở đường cho quân sau',
      'Ghim quân hiệu quả nhất khi quân bị ghim đang che cửu cung',
      'Đẩy binh quá sâu mà không có xe mã phía sau thường chỉ mất nhịp',
      'Đổi hết quân che chắn có thể làm pháo mất ngòi và mất lực công',
      'Thấy lợi nhỏ mà quên đại thế là tự nhường nhịp tiên cho đối phương',
      'Khi đối phương thủ chặt, hãy đổi hướng ép thay vì cố đánh một tuyến đã bít',
      'Song công thường mạnh hơn ăn quân ngay, vì bắt đối phương phải chọn một điểm mất',
    ],
  },
  {
    id: 'tan',
    title: 'Tàn cuộc',
    items: [
      'Tàn cuộc thắng bằng khóa đường tướng trước, ăn quân sau',
      'Binh qua sông cần xe, mã hoặc tướng hỗ trợ mới thành mối đe dọa thật',
      'Xe tàn cuộc mạnh nhất khi cắt đường tướng và ép quân thủ bị động',
      'Pháo tàn cuộc cần ngòi; không có ngòi thì sức ép giảm rất nhanh',
      'Mã tàn cuộc cần điểm đứng gần chiến trường, đi xa dễ để binh bị chặn',
      'Quân ít càng phải đứng gần nhau để tạo thế gọng kìm',
      'Không để xe rời xa binh nếu đối phương còn đủ sĩ tượng thủ cung',
      'Tốt đi quá sâu có thể chặn đường tiến của chính quân mình',
      'Khi hơn quân, ưu tiên đổi quân tấn công của đối phương, giữ quân có khả năng ép tướng',
      'Tướng cũng là quân chiến đấu trong tàn cuộc, cần dùng để giữ mặt và khóa lộ',
      'Một nước chờ đúng lúc có thể buộc đối phương tự phá thế thủ',
      'Đừng vội chiếu liên tục nếu chiếu xong để đối phương đưa tướng về vị trí tốt hơn',
    ],
  },
  {
    id: 'sat',
    title: 'Sát cục',
    items: [
      'Sát cục bắt đầu từ việc khóa ô thoát của tướng',
      'Xe mạnh trong sát cục vì cắt đường chạy, pháo mạnh vì chiếu theo tuyến',
      'Mã dùng để khóa điểm, pháo dùng để đánh tuyến, xe dùng để giữ đường lui',
      'Pháo chỉ thật sự sắc khi có đúng ngòi và tướng nằm trên cùng trục',
      'Binh tiến đúng lúc có thể đẩy tướng vào hàng bất lợi',
      'Ép tướng lên hoặc xuống một hàng thường mở điểm yếu cho xe khai thác',
      'Quân thủ thành của đối phương đôi khi chính là ngòi pháo tốt nhất',
      'Không đổi pháo hoặc mã nếu đó là quân đang giữ đường sát',
      'Chậm một nhịp trong sát cục thường đủ để đối phương dựng sĩ vá cung',
      'Đòn sát hàng đáy phải kiểm tra đủ ô thoát trước khi chiếu',
      'Song pháo cần giữ đúng khoảng cách giữa ngòi và quân chiếu',
      'Khi có thế sát, thời điểm ra đòn quan trọng hơn việc gom thêm vật chất',
    ],
  },
] as const
